package com.example.smackcheck2.data

import io.github.jan.supabase.postgrest.postgrest
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Repository for saving dish entries to Supabase.
 *
 * Handles both AI-detected dishes and manually entered dishes.
 * All database operations use coroutines for non-blocking execution.
 */
object DishRepository {

    // ── Supabase row model for the "dishes" table ──────────────────────────
    @Serializable
    data class SupabaseDishRow(
        val id: String? = null,                      // UUID, auto-generated by Supabase
        val name: String,                             // Dish name (AI-detected or manual)
        @SerialName("restaurant_name")
        val restaurantName: String? = null,           // Optional restaurant name
        val description: String? = null,              // Optional description / comment
        val rating: Float? = null,                    // 0–5 star rating
        @SerialName("image_url")
        val imageUrl: String? = null,                 // Captured photo URI / URL
        @SerialName("user_id")
        val userId: String? = null,                   // ID of the user who submitted
        @SerialName("is_manual_entry")
        val isManualEntry: Boolean = false,           // true when added via fallback
        @SerialName("ai_confidence")
        val aiConfidence: Float? = null,              // AI confidence score (null for manual)
        @SerialName("created_at")
        val createdAt: String? = null                 // Timestamp, auto-set by Supabase
    )

    /**
     * Save a dish entry to the Supabase "dishes" table.
     *
     * @param dishName       The name of the dish
     * @param restaurantName Optional restaurant where the dish was found
     * @param description    Optional text description / comment
     * @param rating         Star rating (0f–5f)
     * @param imageUri       URI of the captured photo
     * @param isManualEntry  Whether this was a manual fallback entry
     * @param aiConfidence   AI detection confidence (null for manual)
     * @return true if the insert succeeded, false otherwise
     */
    suspend fun saveDish(
        dishName: String,
        restaurantName: String? = null,
        description: String? = null,
        rating: Float? = null,
        imageUri: String? = null,
        isManualEntry: Boolean = false,
        aiConfidence: Float? = null
    ): Boolean {
        return try {
            val row = SupabaseDishRow(
                name = dishName,
                restaurantName = restaurantName,
                description = description,
                rating = rating,
                imageUrl = imageUri,
                isManualEntry = isManualEntry,
                aiConfidence = aiConfidence
            )

            // Insert into the "dishes" table
            SupabaseClient.client.postgrest
                .from("dishes")
                .insert(row)

            true
        } catch (e: Exception) {
            // Log the error for debugging; caller handles the failure
            println("DishRepository.saveDish error: ${e.message}")
            false
        }
    }
}
