-- VERIFICATION SCRIPT
-- Run this after executing definitive_uuid_to_text_fix.sql
-- to verify all UUID columns have been converted to TEXT

-- ==================== COLUMN TYPE VERIFICATION ====================
SELECT
    table_name,
    column_name,
    data_type,
    column_default,
    CASE
        WHEN data_type = 'text' THEN '✓ CORRECT'
        ELSE '✗ STILL UUID - MIGRATION INCOMPLETE'
    END as status
FROM information_schema.columns
WHERE table_schema = 'public'
AND column_name IN ('id', 'user_id', 'dish_id', 'restaurant_id', 'rating_id', 'badge_id', 'challenge_id', 'review_id')
ORDER BY
    CASE WHEN data_type != 'text' THEN 0 ELSE 1 END,  -- Show errors first
    table_name,
    column_name;

-- ==================== FOREIGN KEY CONSTRAINT VERIFICATION ====================
SELECT
    tc.table_name,
    kcu.column_name,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name,
    '✓ FK Exists' as status
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
    ON tc.constraint_name = kcu.constraint_name
    AND tc.table_schema = kcu.table_schema
JOIN information_schema.constraint_column_usage AS ccu
    ON ccu.constraint_name = tc.constraint_name
    AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
AND tc.table_schema = 'public'
ORDER BY tc.table_name, kcu.column_name;

-- ==================== INDEX VERIFICATION ====================
SELECT
    schemaname,
    tablename,
    indexname,
    '✓ Index Exists' as status
FROM pg_indexes
WHERE schemaname = 'public'
AND (
    indexname LIKE 'idx_ratings_%'
    OR indexname LIKE 'idx_dishes_%'
    OR indexname LIKE 'idx_likes_%'
    OR indexname LIKE 'idx_user_badges_%'
    OR indexname LIKE 'idx_restaurants_%'
    OR indexname LIKE 'idx_reviews_%'
    OR indexname LIKE 'idx_review_likes_%'
    OR indexname LIKE 'idx_user_challenges_%'
)
ORDER BY tablename, indexname;

-- ==================== FUNCTION VERIFICATION ====================
SELECT
    routine_name,
    routine_type,
    '✓ Function Exists' as status
FROM information_schema.routines
WHERE routine_schema = 'public'
AND routine_name = 'generate_text_id';

-- ==================== TEST ID GENERATION ====================
-- This will show sample IDs generated by the function
SELECT
    'dish_' || substring(md5(random()::text), 1, 20) as sample_dish_id,
    'rating_' || substring(md5(random()::text), 1, 20) as sample_rating_id,
    'rst_' || substring(md5(random()::text), 1, 20) as sample_restaurant_id;

-- ==================== ROW LEVEL SECURITY VERIFICATION ====================
SELECT
    schemaname,
    tablename,
    rowsecurity,
    CASE
        WHEN rowsecurity THEN '✓ RLS Enabled'
        ELSE '✗ RLS Disabled'
    END as status
FROM pg_tables
WHERE schemaname = 'public'
AND tablename IN ('profiles', 'badges', 'user_badges', 'restaurants', 'dishes', 'ratings', 'likes', 'reviews', 'challenges', 'review_likes', 'user_challenges')
ORDER BY tablename;

-- ==================== SUMMARY ====================
-- Count total columns that should be TEXT
WITH expected_columns AS (
    SELECT COUNT(*) as total
    FROM information_schema.columns
    WHERE table_schema = 'public'
    AND column_name IN ('id', 'user_id', 'dish_id', 'restaurant_id', 'rating_id', 'badge_id', 'challenge_id', 'review_id')
),
text_columns AS (
    SELECT COUNT(*) as text_count
    FROM information_schema.columns
    WHERE table_schema = 'public'
    AND column_name IN ('id', 'user_id', 'dish_id', 'restaurant_id', 'rating_id', 'badge_id', 'challenge_id', 'review_id')
    AND data_type = 'text'
)
SELECT
    e.total as total_columns,
    t.text_count as columns_converted_to_text,
    (e.total - t.text_count) as columns_still_uuid,
    CASE
        WHEN e.total = t.text_count THEN '✓✓✓ MIGRATION COMPLETE ✓✓✓'
        ELSE '✗✗✗ MIGRATION INCOMPLETE - ' || (e.total - t.text_count)::text || ' columns still need conversion ✗✗✗'
    END as migration_status
FROM expected_columns e, text_columns t;
